config/routes.rb
Rails.application.routes.draw do
  resources :instagram_accounts, path: :accounts do
    resources :posts, only: [:new, :create, :edit, :update, :destroy]
  end

  get "pricing", to: "home#pricing"

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root "home#index", as: :authenticated_root
    end

    unauthenticated do
      root "home#landing_page", as: :unauthenticated_root
    end
  end
end

app/models/instagram_account.rb
class InstagramAccount < ApplicationRecord
  belongs_to :user

  has_many :posts

  attr_encrypted :password, key: Base64.decode64(Rails.application.secrets.encryption_key)

  validates :user, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validate :valid_credentials

  private

  def valid_credentials
    return unless errors.empty?

    client = InstagramUpload::Client.new(username, password)
    result = client.send(:login)

    if result["status"] == "fail"
      errors.add(:base, :valid_credentials, message: result["message"])
    end
  end
end

app/controllers/instagram_accounts_controller.rb
class InstagramAccountsController < ApplicationController
  before_action :set_instagram_account, only: [:show, :edit, :update, :destroy]

  def index
    @instagram_accounts = current_user.instagram_accounts.all
  end

  def show
  end

  def new
    @instagram_account = current_user.instagram_accounts.build
  end

  def edit
  end

  def create
    @instagram_account = current_user.instagram_accounts.build(instagram_account_params)

    respond_to do |format|
      if @instagram_account.save
        format.html { redirect_to @instagram_account, notice: 'Instagram account was successfully created.' }
        format.json { render :show, status: :created, location: @instagram_account }
      else
        format.html { render :new }
        format.json { render json: @instagram_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @instagram_account.update(instagram_account_params)
        format.html { redirect_to @instagram_account, notice: 'Instagram account was successfully updated.' }
        format.json { render :show, status: :ok, location: @instagram_account }
      else
        format.html { render :edit }
        format.json { render json: @instagram_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @instagram_account.destroy
    respond_to do |format|
      format.html { redirect_to instagram_accounts_url, notice: 'Instagram account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_instagram_account
    @instagram_account = current_user.instagram_accounts.find(params[:id])
  end

  def instagram_account_params
    params.require(:instagram_account).permit(:username, :password)
  end
end

app/views/instagram_accounts/_form.html.erb
<%= errors_for(instagram_account) %>

<%= form_with(model: instagram_account, local: true) do |form| %>
  <%= form.label :username, "Instagram Username" %>
  <%= form.text_field :username, id: :instagram_account_username, autofocus: true, class: "u-full-width" %>

  <%= form.label :password %>
  <%= form.password_field :password, id: :instagram_account_password, class: "u-full-width" %>

  <%= form.submit "Add", class: "button-primary" %>
<% end %>

<p><small>Due to limitations and restrictions in Instagram API we need to sign you through your Instagram username and password. Your details are stored securely in our system and can't be accessed or read by anyone else. In other words your account is safe with us and you can save time by scheduling and posting your images.</small></p>

app/views/instagram_accounts/edit.html.erb
<h1>Editing Instagram Account</h1>

<%= render 'form', instagram_account: @instagram_account %>

<%= link_to 'Show', @instagram_account %> |
<%= link_to 'Back', instagram_accounts_path %>

app/views/instagram_accounts/index.html.erb
<h1>Instagram Accounts</h1>

<%= link_to 'Add new', new_instagram_account_path, class: "button #{current_user.instagram_accounts.any? ? "" : "button-primary"}" %>

<table class="u-full-width instagram-accounts">
  <thead>
    <tr>
      <th></th>
      <th class="actions"></th>
    </tr>
  </thead>

  <tbody>
    <% @instagram_accounts.each do |instagram_account| %>
      <tr>
        <td><%= link_to "@#{instagram_account.username}", instagram_account %></td>
        <td><%= link_to 'Publish', new_instagram_account_post_path(instagram_account), class: "button button-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instagram_accounts/new.html.erb
<h1>Connect Instagram Account</h1>

<%= render 'form', instagram_account: @instagram_account %>

<% if current_user.instagram_accounts.size > 1  %>
  <%= link_to 'Back', instagram_accounts_path %>
<% end %>

app/views/instagram_accounts/show.html.erb
<h2>@<%= @instagram_account.username %></h2>

<div class="space-between">
  <%= link_to 'Schedule', new_instagram_account_post_path(@instagram_account), class: "button button-primary"  %>
  <%= link_to 'Switch accounts', instagram_accounts_path, class: "button" %>
</div>

<% if @instagram_account.posts.any? %>
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Image</th>
        <th>Scheduled at</th>
        <th>Published at</th>
      </tr>
    </thead>

    <tbody>
      <% @instagram_account.posts.order(scheduled_at: :desc).each do |post| %>
        <tr>
          <td><%= image_tag(post.picture.thumb.url, height: 150, width: 150) %></td>
          <td><%= (post.published_at || post.message).present? ? post.scheduled_at.to_formatted_s(:long) : link_to(post.scheduled_at.to_formatted_s(:long), edit_instagram_account_post_path(@instagram_account, post)) %></td>
          <td><%= post.message || post.published_at.try(:to_formatted_s, :long) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>


<p>@<%= @instagram_account.username %> | <%= link_to 'Edit', edit_instagram_account_path(@instagram_account) %></p>