config/routes.rb
Rails.application.routes.draw do
  resources :instagram_accounts, path: :accounts do
    resources :posts, only: [:new, :create, :edit, :update, :destroy]
  end

  get "pricing", to: "home#pricing"

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root "home#index", as: :authenticated_root
    end

    unauthenticated do
      root "home#landing_page", as: :unauthenticated_root
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :picture, PictureUploader

  belongs_to :instagram_account

  validates :title, presence: true, length: { maximum: 2000 }
  validates :picture, presence: true
  validates :scheduled_at, presence: true
  validates :instagram_account, presence: true

  validate :check_aspect_ratio, on: :create

  private

  def check_aspect_ratio
    if !picture_cache.nil?
      if picture.width > picture.height
        if picture.width / picture.height.to_f > 1.91
          errors.add(:picture, "supports aspect ratio up to 1.91:1 for landscapes. Your one is too wide.")
        end
      elsif picture.width < picture.height
        if picture.width / picture.height.to_f < 0.8
          errors.add(:picture, "supports aspect ratio up to 4:5 for portraits. Your one is too narrow.")
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_instagram_account
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :check_instagram_account_presence

  def new
    @post = @instagram_account.posts.new(scheduled_at: Time.now)
  end

  def edit
  end

  def create
    @post = @instagram_account.posts.new(post_params)
    @post.picture = params[:post][:file]

    respond_to do |format|
      if @post.save
        format.html { redirect_to instagram_account_path(@instagram_account), notice: 'Picture was scheduled successfully.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to instagram_account_path(@instagram_account), notice: 'Picture was scheduled successfully.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to instagram_account_path(@instagram_account), notice: 'Picture was deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_instagram_account
    @instagram_account = current_user.instagram_accounts.find(params[:instagram_account_id])
  end

  def set_post
    @post = @instagram_account.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :scheduled_at)
  end
end

app/views/posts/_form.html.erb
<%= errors_for(post) %>

<%= form_with(model: [post.instagram_account, post], local: true) do |form| %>
  <%= form.label :title, "Caption" %>
  <%= form.text_area :title, id: :post_title, autofocus: true, class: "u-full-width" %>

  <% if post.new_record? %>
    <%= form.label :file, "Picture" %>
    <%= form.file_field :file, class: "u-full-width" %>
  <% else %>
    <%= image_tag(post.picture.thumb.url, height: 150, width: 150) %>
  <% end %>

  <%= form.label :scheduled_at %>
  <%= form.datetime_select :scheduled_at, id: :post_scheduled_at %>

  <%= form.submit "Schedule", class: "button-primary" %>
<% end %>

<p><strong>Pro tip:</strong> If you want to publish your picture now leave the current time as is and it gets published within the next 10 minutes.</p>

app/views/posts/edit.html.erb
<h1>Edit picture</h1>

<%= render 'form', post: @post %>

<div class="space-between">
  <%= link_to 'Back', instagram_account_path(@post.instagram_account) %>
  <%= link_to 'Delete', instagram_account_post_path(@post.instagram_account), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/posts/new.html.erb
<h1>Add picture</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', instagram_account_path(@post.instagram_account) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Filepath:</strong>
  <%= @post.filepath %>
</p>

<p>
  <strong>Scheduled at:</strong>
  <%= @post.scheduled_at %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>

<p>
  <strong>Instagram account:</strong>
  <%= @post.instagram_account %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>